'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import AppShell from './components/AppShell';
import Login from './components/Login';
import {api,Campaign,statusTone,User} from '@/lib/api';

export default function Dashboard(){
  const [user,setUser]=useState<User|null|undefined>();const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [filter,setFilter]=useState('All');
  useEffect(()=>{api<User>('/auth/me').then(u=>{setUser(u);return api<Campaign[]>('/campaigns')}).then(setCampaigns).catch(()=>setUser(null))},[]);
  const visible=useMemo(()=>filter==='All'?campaigns:campaigns.filter(c=>filter==='Active'?['RUNNING','SCHEDULED'].includes(c.status):c.status===filter.toUpperCase()),[campaigns,filter]);
  if(user===undefined)return <div className="login"><div className="card login-card"><div className="skeleton" style={{width:'40%',height:34}}/><div className="skeleton" style={{marginTop:25,height:90}}/></div></div>;
  if(!user)return <Login/>;
  const totals=campaigns.reduce((a,c)=>({contacts:a.contacts+c.total_count,sent:a.sent+c.sent_count,replies:a.replies+c.replied_count,active:a.active+Number(['RUNNING','SCHEDULED'].includes(c.status))}),{contacts:0,sent:0,replies:0,active:0});
  return <AppShell user={user}><div className="page"><div className="page-header"><div><div className="eyebrow">Campaigns</div><h1 className="title">Your outreach, at a glance</h1><p className="subtitle">Create personalized Gmail campaigns and follow up automatically until they reply.</p></div><Link className="btn primary" href="/campaigns/new">＋ New campaign</Link></div><section className="stats"><div className="card stat-card"><div className="stat-label">Active campaigns</div><div className="stat-value">{totals.active}</div><div className="stat-note">Currently sending or scheduled</div></div><div className="card stat-card"><div className="stat-label">Total contacts</div><div className="stat-value">{totals.contacts}</div><div className="stat-note">Across all campaigns</div></div><div className="card stat-card"><div className="stat-label">Emails sent</div><div className="stat-value">{totals.sent}</div><div className="stat-note">Includes follow-up steps</div></div><div className="card stat-card"><div className="stat-label">Replies</div><div className="stat-value">{totals.replies}</div><div className="stat-note">Sequences stopped automatically</div></div></section><section className="card"><div className="toolbar"><div className="tabs">{['All','Active','Paused','Completed'].map(x=><button key={x} className={`tab ${filter===x?'active':''}`} onClick={()=>setFilter(x)}>{x}</button>)}</div></div>{visible.length?<div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Recipients</th><th>Emails sent</th><th>Replies</th><th>Status</th><th>Scheduled</th></tr></thead><tbody>{visible.map(c=><tr key={c.id}><td><Link className="campaign-name" href={`/campaigns/${c.id}`}>{c.name}</Link><div className="hint">{c.source==='SHEET'?'Google Sheets':c.source==='CSV'?'CSV import':'Manual contacts'}</div></td><td>{c.total_count}</td><td>{c.sent_count}</td><td>{c.replied_count}</td><td><span className={`badge ${statusTone(c.status)}`}>{c.status.toLowerCase()}</span></td><td>{new Date(c.scheduled_at).toLocaleString()}</td></tr>)}</tbody></table></div>:<div className="empty"><div className="empty-mark">➤</div><h2>No campaigns here yet</h2><p className="subtitle">Import a few contacts and send your first personalized campaign.</p><Link className="btn primary" href="/campaigns/new">Create campaign</Link></div>}</section></div></AppShell>;
}
